_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
num_topics:
    value: 3
passes:
    value: 10
random_state:
    value: 42
